export type PipelineStage = 'node_generation' | 'credential_injection' | 'connection_wiring' | 'workflow_structure' | 'expression_syntax'

export const VALIDATOR_RULE_IDS: number[] = [
  ...Array.from({ length: 63 }, (_, i) => i + 1),  // 1-63
  ...Array.from({ length: 39 }, (_, i) => i + 65), // 65-103 (64 skipped — conflicts with Kairos prompt; 104 deferred)
  ...Array.from({ length: 22 }, (_, i) => i + 105), // 105-126 (104 skipped)
  127, 128, // Phase 4 (n8n-skills gap analysis): Code language/param mismatch, unwired error-output port
  129, // Phase 5 (node property-schema enrichment): resource/operation value doesn't exist for the node type
  130, // Phase 4 judgment call #2: AWS S3 / Slack file upload missing binaryPropertyName (Rule 57's pattern, extended)
]

export const RULE_PIPELINE_STAGES: Record<number, PipelineStage> = {
  1: 'node_generation',
  2: 'node_generation',
  3: 'node_generation',
  4: 'node_generation',
  5: 'node_generation',
  6: 'node_generation',
  7: 'node_generation',
  8: 'node_generation',
  9: 'connection_wiring',
  10: 'connection_wiring',
  11: 'connection_wiring',
  12: 'workflow_structure',
  13: 'node_generation',
  14: 'workflow_structure',
  15: 'node_generation',
  16: 'node_generation',
  17: 'credential_injection',
  18: 'connection_wiring',
  19: 'node_generation',
  20: 'connection_wiring',
  21: 'workflow_structure',
  22: 'workflow_structure',
  23: 'node_generation',
  24: 'expression_syntax',
  25: 'expression_syntax',
  26: 'expression_syntax',
  27: 'node_generation',
  28: 'node_generation',
  29: 'node_generation',
  30: 'node_generation',
  31: 'node_generation',
  32: 'node_generation',
  33: 'node_generation',
  34: 'node_generation',
  35: 'node_generation',
  36: 'expression_syntax',
  37: 'node_generation',
  38: 'connection_wiring',
  39: 'node_generation',
  40: 'node_generation',
  41: 'node_generation',
  42: 'connection_wiring',
  43: 'node_generation',
  44: 'node_generation',
  45: 'connection_wiring',
  46: 'credential_injection',
  47: 'connection_wiring',
  48: 'node_generation',
  49: 'node_generation',
  50: 'node_generation',
  51: 'node_generation',
  52: 'node_generation',
  53: 'connection_wiring',
  54: 'credential_injection',
  55: 'node_generation',
  56: 'node_generation',
  57: 'node_generation',
  58: 'credential_injection',
  59: 'node_generation',
  60: 'node_generation',
  61: 'node_generation',
  62: 'node_generation',
  63: 'node_generation',
  65: 'node_generation',
  66: 'node_generation',
  67: 'expression_syntax',
  68: 'node_generation',
  69: 'node_generation',
  70: 'node_generation',
  71: 'node_generation',
  72: 'node_generation',
  73: 'node_generation',
  74: 'node_generation',
  75: 'node_generation',
  76: 'node_generation',
  77: 'expression_syntax',
  78: 'workflow_structure',
  79: 'node_generation',
  80: 'node_generation',
  81: 'connection_wiring',
  82: 'connection_wiring',
  83: 'node_generation',
  84: 'node_generation',
  85: 'credential_injection',
  86: 'node_generation',
  87: 'connection_wiring',
  88: 'node_generation',
  89: 'connection_wiring',
  90: 'connection_wiring',
  91: 'node_generation',
  92: 'expression_syntax',
  93: 'expression_syntax',
  94: 'node_generation',
  95: 'node_generation',
  96: 'connection_wiring',
  97: 'connection_wiring',
  98: 'node_generation',
  99: 'node_generation',
  100: 'node_generation',
  101: 'node_generation',
  102: 'node_generation',
  103: 'node_generation',
  105: 'node_generation',
  106: 'connection_wiring',
  107: 'expression_syntax',
  108: 'node_generation',
  109: 'node_generation',
  110: 'node_generation',
  111: 'connection_wiring',
  112: 'expression_syntax',
  113: 'connection_wiring',
  114: 'expression_syntax',
  115: 'connection_wiring',
  116: 'node_generation',
  117: 'node_generation',
  118: 'node_generation',
  119: 'node_generation',
  120: 'node_generation',
  121: 'node_generation',
  122: 'expression_syntax',
  123: 'node_generation',
  124: 'node_generation',
  125: 'expression_syntax',
  126: 'node_generation',
  127: 'node_generation',
  128: 'connection_wiring',
  129: 'node_generation',
  130: 'node_generation',
}

export interface RuleExample {
  bad: string
  good: string
}

export const RULE_EXAMPLES: Record<number, RuleExample> = {
  17: {
    bad:  '"credentials": { "slackOAuth2Api": "my-token" }',
    good: '"credentials": { "slackOAuth2Api": { "id": "placeholder-id", "name": "My Slack OAuth" } }',
  },
  24: {
    bad: '$node["Fetch Data"].json.email',
    good: "$('Fetch Data').item.json.email",
  },
  25: {
    bad: '$json.items[0].email',
    good: '$json.email',
  },
  26: {
    bad: "$('Fetch Data').json.email",
    good: "$('Fetch Data').first().json.email",
  },
  27: {
    bad: '"url": "https://example.com/api/data"',
    good: '"url": "https://api.yourservice.com/v1/endpoint"',
  },
  28: {
    bad: '"jsCode": "// TODO: implement this"',
    good: '"jsCode": "return items.map(item => ({ json: { result: item.json.value * 2 } }))"',
  },
  29: {
    bad: '"channelId": ""',
    good: '"channelId": { "__rl": true, "value": "C0123456789", "mode": "id" }',
  },
  30: {
    bad: '"operation": "send", "to": ""',
    good: '"operation": "send", "to": "recipient@example.com"',
  },
  31: {
    bad: '"conditions": { "combinator": "and", "conditions": [] }',
    good: '"conditions": { "combinator": "and", "conditions": [{ "leftValue": "={{ $json.status }}", "rightValue": "active", "operator": { "type": "string", "operation": "equals" } }] }',
  },
  32: {
    bad: '"assignments": { "assignments": [] }',
    good: '"assignments": { "assignments": [{ "id": "f1", "name": "status", "value": "processed", "type": "string" }] }',
  },
  33: {
    bad: '"rule": { "interval": [] }',
    good: '"rule": { "interval": [{ "field": "cronExpression", "expression": "0 9 * * 1-5" }] }',
  },
  34: {
    bad: '"path": "/my webhook"',
    good: '"path": "my-webhook"',
  },
  35: {
    bad: '"type": "n8n-nodes-base.gmail", "parameters": { "operation": "send" }  // no sent_at tracking',
    good: 'Add a Set node after send that writes "sent_at": "={{ $now }}" back to the sheet, or an IF node that checks sent_at before sending',
  },
  36: {
    bad: '// Code node outputs: { json: { contactEmail, facilityName } }\n// Gmail node To field: "={{ $json.contact_email }}"  ← snake_case mismatch',
    good: '// Code node outputs: { json: { contactEmail, facilityName } }\n// Gmail node To field: "={{ $json.contactEmail }}"  ← matches exactly',
  },
  37: {
    bad: 'const date = new Date(row.last_service_date)  // "06-04-26" → Invalid Date',
    good: 'function parseDate(s) { const [m,d,y] = s.split("-"); return new Date(2000+parseInt(y), parseInt(m)-1, parseInt(d)); }',
  },
  38: {
    bad: '// Generate Post 1 ─┐\n// Generate Post 2 ─┼─► Combine All Posts  (parallel fan-in fails)\n// Generate Post 3 ─┘',
    good: '// Generate Post 1 ─► Generate Post 2 ─► Generate Post 3 ─► Combine All Posts  (sequential chain)',
  },
  39: {
    bad: '"model": "claude-3-5-sonnet-20241022"',
    good: '"model": "claude-sonnet-4-6"',
  },
  40: {
    bad: '"documentId": "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgVE2upms"',
    good: '"documentId": { "__rl": true, "mode": "id", "value": "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgVE2upms" }',
  },
  41: {
    bad: '"sendBody": false, "bodyParameters": { "parameters": [{"name": "data", "value": "hello"}] }',
    good: '"sendBody": true, "bodyParameters": { "parameters": [{"name": "data", "value": "hello"}] }',
  },
  42: {
    bad: '// SplitInBatches output 0 → Process Item → SplitInBatches  (loop on done branch)',
    good: '// SplitInBatches output 1 → Process Item → SplitInBatches  (loop on body branch)\n// SplitInBatches output 0 → Send Summary  (done branch runs once after all batches)',
  },
  43: {
    bad: '{ "leftValue": "={{ $json.status }}", "rightValue": "active", "operator": "equals" }',
    good: '{ "leftValue": "={{ $json.status }}", "rightValue": "active", "operator": { "type": "string", "operation": "equals" } }',
  },
  44: {
    bad: '"columnMappingMode": "defineBelow", "fieldsUi": { "values": [] }',
    good: '"columnMappingMode": "defineBelow", "fieldsUi": { "values": [{"fieldId": "email", "fieldValue": "={{ $json.email }}"}] }',
  },
  45: {
    bad: '// AI Agent node has no ai_languageModel connection pointing to it',
    good: '"OpenAI Chat Model": { "ai_languageModel": [ [{ "node": "AI Agent", "type": "ai_languageModel", "index": 0 }] ] }',
  },
  46: {
    bad: '"headerParameters": { "parameters": [{ "name": "Authorization", "value": "Bearer sk-1234567890abcdefghijklmnop" }] }',
    good: '"credentials": { "openAiApi": { "id": "placeholder-id", "name": "My OpenAI Credential" } }',
  },
  47: {
    bad: '// Switch has 3 routes but connections only wire output 0 and 1 — route 2 items silently dropped',
    good: '// All Switch output routes connected: main[0], main[1], main[2] each point to a downstream node',
  },
  48: {
    bad: '"model": "gpt-3.5-turbo"',
    good: '"model": "gpt-4o-mini"',
  },
  49: {
    bad: '{ "type": "n8n-nodes-base.executeWorkflow", "parameters": {} }',
    good: '{ "type": "n8n-nodes-base.executeWorkflow", "parameters": { "workflowId": "123" } }',
  },
  50: {
    bad: '// scheduleTrigger → AI Agent (promptType: "auto") — no chatTrigger present',
    good: '// Either add @n8n/n8n-nodes-langchain.chatTrigger, or set promptType: "define" with a text parameter',
  },
  51: {
    bad: '"resume": "webhook"  // Wait node with no node downstream sending $execution.resumeUrl',
    good: '// Add a Gmail or HTTP Request node after the trigger path that sends $execution.resumeUrl to the approver',
  },
  52: {
    bad: 'const query = `SELECT * FROM users WHERE email = \'${$json.email}\'`',
    good: 'const query = { sql: "SELECT * FROM users WHERE email = $1", values: [$json.email] }',
  },
  53: {
    bad: '"mode": "chooseBranch"  // with only 1 incoming main connection — hangs forever',
    good: '"mode": "chooseBranch"  // ensure 2 upstream branches both connect to this Merge node',
  },
  54: {
    bad: '// httpRequest to api.stripe.com with no credentials and no Authorization header',
    good: '"credentials": { "stripeApi": { "id": "placeholder-id", "name": "Stripe" } }',
  },
  55: {
    bad: '"sheetName": { "__rl": true, "mode": "name", "value": "Sheet1" }  // default placeholder',
    good: '"sheetName": { "__rl": true, "mode": "name", "value": "Customers" }  // actual tab name',
  },
  56: {
    bad: '"onError": "continueRegularOutput"  // no downstream node checks $json.error',
    good: '// Add an IF node after with condition: $json.error exists → handle error branch',
  },
  57: {
    bad: '"sendBody": true, "contentType": "binaryData", "inputDataFieldName": ""  // typeVersion 3+',
    good: '"sendBody": true, "contentType": "binaryData", "inputDataFieldName": "data"  // typeVersion 3+ (use "binaryPropertyName" instead for typeVersion 1-2)',
  },
  58: {
    bad: '"credentials": { "gmailOAuth": { "id": "x", "name": "Gmail" } }  // wrong key for Gmail node',
    good: '"credentials": { "gmailOAuth2": { "id": "x", "name": "Gmail" } }  // correct key',
  },
  59: {
    bad: '"authentication": "none"  // anyone with the URL can trigger this webhook',
    good: '"authentication": "headerAuth"  // caller must provide the configured header token',
  },
  60: {
    bad: '"expression": "* * * * *"  // fires every minute',
    good: '"expression": "0 9 * * 1-5"  // fires weekdays at 9am',
  },
  61: {
    bad: '{ "type": "@n8n/n8n-nodes-langchain.toolWorkflow", "parameters": {} }  // no description',
    good: '{ "type": "@n8n/n8n-nodes-langchain.toolWorkflow", "parameters": { "description": "Looks up the current stock price for a given ticker symbol" } }',
  },
  63: {
    bad: '// Two webhook nodes both use path="order-intake" and method="POST"',
    good: '// First: path="order-intake", method="POST" | Second: path="order-update", method="POST"',
  },
  65: {
    bad: '"batchSize": 0  // throws at runtime',
    good: '"batchSize": 10',
  },
  66: {
    bad: '"url": "api.stripe.com/v1/charges"  // missing protocol',
    good: '"url": "https://api.stripe.com/v1/charges"',
  },
  67: {
    bad: "// Code node: return $('Fetch Customers').all()  ← node renamed to 'Get Customers'",
    good: "// Code node: return $('Get Customers').all()  ← matches actual node name",
  },
  72: {
    bad: 'const data = JSON.parse($json.payload)  // throws on bad JSON',
    good: 'let data; try { data = JSON.parse($json.payload) } catch(e) { return [{ json: { error: e.message } }] }',
  },
  86: {
    bad: '"expression": "9 * * *"  // 4 fields — missing day or month',
    good: '"expression": "0 9 * * *"  // 5 fields: minute hour day month weekday',
  },
  84: {
    bad: '// toolWorkflow inline nodes: [{ type: "n8n-nodes-base.set", ... }]  ← no entry point',
    good: '// toolWorkflow inline nodes: [{ type: "n8n-nodes-base.executeWorkflowTrigger", ... }, { type: "n8n-nodes-base.set", ... }]',
  },
  89: {
    bad: '// chainRetrievalQa node with only an ai_languageModel connection — no ai_retriever',
    good: '"Vector Store Retriever": { "ai_retriever": [ [{ "node": "My QA Chain", "type": "ai_retriever", "index": 0 }] ] }',
  },
  90: {
    bad: '// Webhook trigger: responseMode="lastNode" — but respondToWebhook node exists in flow',
    good: '// Webhook trigger: responseMode="responseNode" — respondToWebhook node sends the response',
  },
  92: {
    bad: '"value": "={{ $now.toISOString() }}"  // Luxon has no .toISOString()',
    good: '"value": "={{ $now.toISO() }}"  // correct Luxon method',
  },
  93: {
    bad: '"value": "={{ $now.format(\'YYYY-MM-DD\') }}"  // Moment.js API — not available on Luxon',
    good: '"value": "={{ $now.toFormat(\'yyyy-MM-dd\') }}"  // Luxon API with lowercase tokens',
  },
  95: {
    bad: '{ "type": "@n8n/n8n-nodes-langchain.toolHttpRequest", "parameters": {} }  // no url',
    good: '{ "type": "@n8n/n8n-nodes-langchain.toolHttpRequest", "parameters": { "url": "https://api.example.com/search", "description": "Searches the catalog" } }',
  },
  97: {
    bad: '// vectorStorePinecone node with only main data flow — no embeddings sub-node connected',
    good: '"Embeddings OpenAI": { "ai_embedding": [ [{ "node": "Pinecone Vector Store", "type": "ai_embedding", "index": 0 }] ] }',
  },
  99: {
    bad: '"prompt": "Extract the following data:\\n{question}"  // output parser connected but no {format_instructions}',
    good: '"prompt": "Extract the following data:\\n{question}\\n\\n{format_instructions}"',
  },
  100: {
    bad: '"operation": "executeQuery", "query": ""  // empty — database throws syntax error',
    good: '"operation": "executeQuery", "query": "SELECT id, name FROM customers WHERE active = true"',
  },
  102: {
    bad: '{ "type": "n8n-nodes-base.splitOut", "parameters": {} }  // missing fieldToSplitOut',
    good: '{ "type": "n8n-nodes-base.splitOut", "parameters": { "fieldToSplitOut": "items" } }',
  },
  103: {
    bad: 'return [{ name: item.name, email: item.email }]  // missing json wrapper — $json.name will be undefined downstream',
    good: 'return [{ json: { name: item.name, email: item.email } }]',
  },
  112: {
    bad: "$now.add(1, 'day')  // Moment.js method — throws TypeError on Luxon DateTime",
    good: '$now.plus({ days: 1 })',
  },
  116: {
    bad: '{ "type": "@n8n/n8n-nodes-langchain.lmChatOpenAi", "parameters": { "model": "claude-sonnet-4-6" } }  // Claude model in OpenAI node',
    good: '{ "type": "@n8n/n8n-nodes-langchain.lmChatAnthropic", "parameters": { "model": "claude-sonnet-4-6" } }',
  },
  125: {
    bad: "$now.toFormat('YYYY-MM-DD')  // YYYY = ISO week year, DD = ordinal day — wrong values",
    good: "$now.toFormat('yyyy-MM-dd')  // lowercase tokens give calendar year and day-of-month",
  },
  105: {
    bad: '"model": "latest"  // not a valid model identifier — API returns "Unknown model"',
    good: '"model": "claude-sonnet-4-6"  // exact model identifier required',
  },
  127: {
    bad: '"language": "python", "jsCode": "return [{ json: {} }]"  // ignored — n8n runs pythonCode for Python',
    good: '"language": "python", "pythonCode": "return [{ \'json\': {} }]"',
  },
  128: {
    bad: '"onError": "continueErrorOutput"  // node has 2 output ports; connections only wire index 0',
    good: '"Node": { "main": [ [{"node": "OnSuccess", ...}], [{"node": "OnError", ...}] ] }  // index 1 wired too',
  },
  129: {
    bad: '"resource": "channels"  // n8n-nodes-base.slack has no "channels" resource (it\'s "channel")',
    good: '"resource": "channel", "operation": "create"',
  },
  130: {
    bad: '"resource": "file", "operation": "upload", "binaryPropertyName": ""',
    good: '"resource": "file", "operation": "upload", "binaryPropertyName": "data"',
  },
}

export const RULE_MITIGATIONS: Record<number, string> = {
  1: 'Provide a non-empty workflow name string',
  2: 'Include at least one node in the nodes array',
  3: 'Every node must have a unique UUID v4 string as its id field',
  4: 'Ensure all node ids are unique — no two nodes can share the same id',
  5: 'Every node must have a non-empty type string',
  6: 'Every node must have a positive integer typeVersion',
  7: 'Every node must have a position array of exactly [x, y] numbers',
  8: 'Every node must have a non-empty name string',
  9: 'connections must be a plain object (use {} if no connections)',
  10: 'Every node name in connections (source and target) must exactly match a name in the nodes array',
  11: 'Every non-trigger node should have at least one incoming connection',
  12: 'Remove forbidden fields: id, active, createdAt, updatedAt, versionId, meta, tags — these are server-assigned',
  13: 'workflow.settings must be a plain object if present',
  14: 'Include at least one trigger node (e.g. scheduleTrigger, webhookTrigger, manualTrigger, or service-specific)',
  15: 'Node type strings must be fully qualified: "n8n-nodes-base.httpRequest" not just "httpRequest"',
  16: 'All node names must be unique within the workflow',
  17: 'Each credential entry must be keyed by credential type with an object value: { "slackOAuth2Api": { "id": "placeholder-id", "name": "My Credential" } } — the key is the credential type, the value has id and name strings',
  18: 'AI sub-nodes (languageModel, memory, tool) must be the CONNECTION SOURCE pointing TO the agent — not the reverse',
  19: 'Use known safe typeVersion values for each node type',
  20: 'Remove connection cycles — ensure no node can reach itself through the connection graph',
  21: 'When using webhook with responseMode "responseNode", include a respondToWebhook node in the flow',
  22: 'Ensure all required parameters are set for each node type (e.g. webhook needs httpMethod and path)',
  23: 'Use node types that exist in the n8n registry — check with kairos_sync',
  24: 'Use modern accessor syntax: $("NodeName").item.json.field instead of deprecated $node["NodeName"].json.field',
  25: 'Access item fields directly with $json.field — n8n flattens items automatically, do not use $json.items[0]',
  26: 'Use $("NodeName").first().json.field or $("NodeName").all() — bare $("NodeName").json without .first() or .all() throws at runtime',
  27: 'Replace placeholder URLs with your actual API endpoint — do not use "example.com" or "YOUR_URL" patterns',
  28: 'Add executable code to the code node — empty or comment-only code nodes do nothing at runtime',
  29: 'Set the channel parameter for Slack message operations (channelId with __rl object, or channel as string)',
  30: 'Set the to parameter for Gmail send operations with at least one recipient email address',
  31: 'Add at least one condition to the if node — conditions.conditions array must be non-empty',
  32: 'Add field assignments to the set node — assignments.assignments array must be non-empty for typeVersion 3.x',
  33: 'Add at least one schedule rule to scheduleTrigger — rule.interval array must have at least one entry',
  34: 'Webhook path must be a relative path without spaces, leading slashes, or protocol prefixes (e.g. "my-hook")',
  35: 'Add duplicate-prevention to email-sending workflows: a sent_at timestamp field updated after each send, or an IF node that checks prior-send status before sending',
  36: 'Ensure field names in the Code node json output match exactly what downstream nodes reference via $json.xxx — camelCase outputs require camelCase expressions, snake_case outputs require snake_case expressions',
  37: 'Replace new Date(externalString) with a parseDate() helper that splits the string and calls new Date(year, month-1, day) — this handles MM-DD-YY and other non-ISO formats reliably',
  38: 'Chain AI HTTP Request calls sequentially (Post1 → Post2 → Post3 → Merge) instead of fanning out in parallel — n8n cannot reference a node that has not yet executed in the current execution path',
  39: 'Update the model name to a current Claude release: claude-sonnet-4-6, claude-opus-4-8, or claude-haiku-4-5-20251001',
  40: 'Use the __rl resource locator format for node parameters that reference external resources: { "__rl": true, "mode": "id", "value": "ACTUAL_ID" } — not a plain string',
  41: 'Set sendBody: true on the HTTP Request node when you include body content — without it, the body is silently ignored',
  42: 'SplitInBatches output 0 = "done" (runs once after all batches finish); output 1 = "loop body" (runs per item). Connect the per-item processing to output 1, not output 0.',
  43: 'typeVersion 2+ IF and Filter nodes require operator as an object: { "type": "string", "operation": "equals" } — not a plain string like "equals"',
  44: 'When using columnMappingMode "defineBelow" on a Google Sheets append/update node, add at least one entry to fieldsUi.values — an empty array writes nothing',
  45: 'Connect an ai_languageModel sub-node (e.g. lmChatAnthropic or lmChatOpenAi) to every AI Agent, chainLlm, chainRetrievalQa, or chainSummarization node',
  46: 'Move credentials from header parameter values into an n8n credential — never put raw API keys, Bearer tokens, or secrets in headerParameters.parameters[].value',
  47: 'Connect all Switch output routes to downstream nodes — unconnected routes silently drop matching items with no error',
  48: 'Update the model name to a current OpenAI release: gpt-4o, gpt-4o-mini, o3, or o4-mini',
  49: 'Set the workflowId parameter on executeWorkflow nodes — without it, no sub-workflow runs',
  50: 'Add a @n8n/n8n-nodes-langchain.chatTrigger or n8n-nodes-base.formTrigger to provide the chat input, or change promptType to "define" and set the text parameter explicitly',
  51: 'After the flow that triggers the Wait, send $execution.resumeUrl to the responsible party (via Gmail, SMS, Slack, etc.) so they can resume the execution',
  52: 'Use parameterized queries instead of string interpolation: pass $json values in a separate values/params array and reference them with $1, $2 placeholders',
  53: 'Ensure the Merge node receives at least 2 incoming main connections when using chooseBranch or combine mode — with fewer it will hang waiting indefinitely',
  54: 'Add credentials to the HTTP Request node or configure authentication — calls to known protected APIs (Stripe, Twilio, GitHub, etc.) require auth to succeed',
  55: 'Replace the "Sheet1" placeholder with the actual tab name from your Google Spreadsheet',
  56: 'Add an IF node immediately after the continueOnFail node that checks $json.error — without it, failures are silently swallowed and the workflow log shows success',
  57: 'Set inputDataFieldName (HTTP Request typeVersion 3+) or binaryPropertyName (typeVersion 1-2) to the name of the binary property from the upstream node (e.g. "data", "attachment", "file") — n8n cannot find the binary data without it',
  58: 'Use the correct credential type key for the node type — wrong keys silently fail at runtime. See the credential type reference in the system prompt.',
  59: 'Set webhook authentication to "Header Auth" or "Basic Auth" — without it anyone who knows the URL can trigger the workflow.',
  60: 'Change the schedule interval to something less frequent — a minute field of "*" or minutesInterval=1 fires every minute and floods execution history.',
  61: 'Add a description to the toolWorkflow sub-node explaining what the tool does and when the AI should call it.',
  62: 'Add a sessionKey expression (e.g. $json.sessionId) to memoryBufferWindow so each user or execution gets an isolated memory buffer.',
  63: 'Use distinct webhook paths or HTTP methods for each webhook node — duplicate path+method combinations prevent one webhook from ever firing.',
  65: 'Set batchSize to a positive integer (e.g. 10 or 50) on the SplitInBatches node.',
  66: 'Prefix the HTTP Request URL with https:// (or http:// for internal services) — n8n requires a fully-qualified URL.',
  67: 'Ensure every node name referenced in $("NodeName") exists in the workflow nodes array — typos and renamed nodes cause runtime throws.',
  68: 'Set the timezone field (e.g. "America/New_York") when creating Google Calendar events so the event appears at the correct local time.',
  69: 'Add a subject line to the Gmail send node — emails without a subject are frequently filtered or ignored.',
  70: 'Either disable keepOnlySet if you need upstream fields to pass through, or verify that dropping all upstream fields is intentional.',
  71: 'Set the workflowId on the toolWorkflow node — without it the agent cannot locate the sub-workflow to call.',
  72: 'Wrap JSON.parse() calls in try/catch and return a structured error instead of letting the node throw and halt the workflow.',
  73: 'Add a description to the AI tool sub-node explaining what the tool does so the agent knows when to invoke it.',
  74: 'Use a dynamic sessionKey expression (e.g. $json.sessionId) on each memoryBufferWindow node so they maintain separate buffers.',
  75: 'Ensure the emailSend node has a recipient address, a subject, and a non-empty message body before deploying.',
  76: 'Set the chatId parameter on the Telegram sendMessage node to the target chat or channel ID.',
  77: 'Replace $json with $input.all() and iterate the resulting array — in runOnceForAllItems mode $json only references the first item.',
  78: 'Add an errorWorkflow ID to workflow settings so failures are routed to an error-handling workflow instead of being silently dropped.',
  79: 'Replace the "webhook-test" URL with the production webhook URL — test URLs expire after the test session ends.',
  80: 'Enable "Include Other Input Fields" on the Set node if downstream nodes need fields from before this node, or explicitly re-add required upstream fields in the assignments.',
  81: 'Remove the self-referencing workflowId — a workflow cannot safely call itself without termination conditions and dedicated recursion support.',
  82: 'Avoid nesting SplitInBatches loops; instead flatten the data before looping, or use a Code node for nested iteration.',
  83: 'Define at least one node inside the inline workflow parameter of the toolWorkflow node so the AI tool has something to execute.',
  84: 'Add an executeWorkflowTrigger node to the inline workflow.nodes array — n8n uses this as the mandatory entry point when calling inline sub-workflows from a toolWorkflow tool.',
  85: 'Remove the manual Authorization header and rely solely on the n8n credential, or remove the credential and use only the header — having both can cause conflicting auth.',
  86: 'Fix the cronExpression to have exactly 5 space-separated fields (minute hour day month weekday), e.g. "0 9 * * 1-5".',
  87: 'Use combineByFields (matching on a shared key) instead of combineByPosition when a Filter node is upstream — positional merging breaks when Filter removes items.',
  88: 'Set the text parameter on the Telegram sendMessage node to the message content — an empty text causes a Telegram API error.',
  89: 'Connect a retriever sub-node (e.g. a vectorStore node) to the chainRetrievalQa node via the ai_retriever connection — this is the mandatory data source for retrieval-augmented question answering.',
  90: 'Set the Webhook trigger\'s Response Mode to "Using Respond to Webhook Node" (responseMode: "responseNode") so n8n knows to wait for the respondToWebhook node to send the response.',
  91: 'Add at least one condition to the filter node — an empty filter passes all items through without filtering anything.',
  92: 'Replace .toISOString() with .toISO() — in n8n, $now and $today are Luxon DateTime objects that use the Luxon API, not native JavaScript Date methods.',
  93: 'Replace .format() with .toFormat() — Luxon uses .toFormat() not .format() (the Moment.js method). Also note: Luxon tokens are lowercase: yyyy (year), MM (month), dd (day), not YYYY/DD.',
  94: 'Add executable JavaScript code to the toolCode node so the AI agent has something to run when it invokes this tool.',
  95: 'Set the url parameter on the toolHttpRequest node to the target API endpoint URL (e.g. "https://api.example.com/endpoint").',
  96: 'Remove the extra language model sub-node — n8n agents only use the language model connected at index 0. If you need different models for different tasks, create separate agent nodes.',
  97: 'Connect an embeddings sub-node (e.g. embeddingsOpenAi or embeddingsAnthropic) to the vector store node via the ai_embedding connection — this is required to convert text to vectors for storage and retrieval.',
  98: 'Add a JSON schema to the outputParserStructured node describing the expected output structure. The schema validates and extracts the LLM response into a typed object.',
  99: 'Add {format_instructions} to the chainLlm prompt template where the parser\'s formatting guidance should appear (e.g. "Answer the question: {question}\\n\\n{format_instructions}"). n8n injects the parser\'s format spec into this placeholder at runtime.',
  100: 'Add the SQL statement to the query parameter of the database execute node. For dynamic queries, use parameterized syntax ($1, $2) and pass values separately.',
  101: 'Add at least one form field to the formTrigger node to define what data the form collects from users.',
  102: 'Set fieldToSplitOut to the name of the array field you want to split into individual items (e.g. "items", "results", or "data").',
  103: 'Wrap all Code node return items in the n8n format: return [{ json: { field: value } }]. Without the "json" key, downstream $json references will be undefined because n8n treats your object as the item envelope, not its payload.',
  105: 'Replace the alias with an exact model identifier — use "claude-sonnet-4-6" or "claude-opus-4-8" for Anthropic, "gpt-4o" or "gpt-4o-mini" for OpenAI.',
  106: 'Wire the fallback output port of the Switch node to a handler node (e.g. a Set node logging the unmatched reason, or a NoOp), or disable fallbackOutput if unmatched items should be silently discarded.',
  107: 'Remove the $json reference from the trigger node\'s parameters — trigger nodes have no upstream input, so $json is empty at parameter evaluation time. Access the trigger\'s output data in downstream nodes via $(\'TriggerName\').first().json.fieldName.',
  108: 'Add fields to aggregate in the fieldsToAggregate list, or switch the aggregate mode to "Aggregate All Item Data" if you want all fields combined into one item.',
  109: 'Add field mappings to the Airtable write node to specify which columns to populate — without them the create/update call writes no data.',
  110: 'Set the text field to the user prompt or question the chain should process when using promptType "define". Without it the LLM receives no input.',
  111: 'Connect the language model sub-node to an Agent, chainLlm, chainRetrievalQa, or chainSummarization node via ai_languageModel. Connecting to any other node type is invalid and the connection will be silently ignored.',
  112: 'Replace Moment.js .add()/.subtract() with Luxon equivalents: .plus({ days: 1 }) and .minus({ days: 1 }). Luxon uses an object argument with named duration units.',
  113: 'Connect both the true (port 0) and false (port 1) output branches of the IF node. If items on one branch should be discarded, connect that branch to a NoOp node to make the intent explicit.',
  114: "Update the $('NodeName') expression to reference a node that exists in this workflow. Check for renamed or deleted nodes and update all stale expression references.",
  115: 'Connect the last node in the SplitInBatches processing chain (output 1) back to the SplitInBatches node input. Without the loop-back, only the first batch executes.',
  116: 'Use a model identifier that matches the provider node — claude-* models for lmChatAnthropic, gpt-*/o* models for lmChatOpenAi, gemini-* models for lmChatGoogleGemini. Also ensure the credential matches the provider.',
  117: 'Set both start and end parameters on the Google Calendar create event node to ISO 8601 datetime strings. Both are required by the Google Calendar API.',
  118: 'Set the propertyName parameter on the Redis node to the key you want to operate on. Key-based Redis operations require a non-empty key.',
  119: 'Set tableId to the name of the Supabase table to operate on. Every Supabase operation requires a table name.',
  120: "Set messageId on the Gmail reply node to the ID of the message to reply to (e.g. $('Gmail Trigger').first().json.id). Without it the Gmail API cannot thread the reply.",
  121: 'Remove the dot from fieldToSplitOut — splitOut treats the value as a literal field name, not a dot-path. To split a nested array, first use a Set node to hoist the value to the top level, then reference that top-level field name.',
  122: 'Use the object form for Luxon duration arithmetic: .plus({ days: 1 }) or .minus({ hours: 2 }). The positional (number, unit) form is Moment.js syntax and silently treats the number as milliseconds in Luxon.',
  123: 'Add query parameter name/value pairs to the queryParameters list, or disable sendQuery if no query string is needed.',
  124: 'Add a return statement to the Code node in runOnceForAllItems mode. Without return, the node emits 0 items. Use: return [{ json: { field: value } }].',
  125: "Replace YYYY with yyyy and DD with dd in Luxon .toFormat() calls. Luxon uses lowercase tokens for calendar year and day-of-month — uppercase YYYY means ISO week year and DD means ordinal day of year.",
  126: 'Replace the node ID with a valid UUID v4 (xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx). Use a UUID generator to create a proper random UUID v4.',
  127: 'Move the Code node\'s code into the parameter matching its language setting: pythonCode when language is "python", jsCode otherwise. n8n only executes the parameter matching the language setting.',
  128: 'Wire output index 1 (the error-path port created by onError: "continueErrorOutput") to a node that handles the failure — otherwise every item that errors on this node is silently dropped with nowhere to go.',
  129: 'Use one of this node type\'s actual valid resource/operation values (see the warning message for the exact list) — the value set does not exist for this node type.',
  130: 'Set binaryPropertyName to the name of the binary property from the upstream node (e.g. "data", "attachment") — AWS S3 and Slack file uploads cannot locate the binary data without it.',
}
